server.port=18001

# Service info
service.target_port=18001
service.port=18001
service.host=backend-service.169.56.86.251.nip.io
service.replicas=2

#eureka
eureka.servers="http://eureka-server-0.eureka-server:18761/eureka,http://eureka-server-1.eureka-server:18761/eureka/,http://eureka-server-2.eureka-server:18761/eureka/"
