#!/bin/bash

echo "************* BUILD&PUSH Container image *****************"

# get parameters
if ([ $# -lt 4 ]) || ([ $# -eq 1 ] && [ "$1" == "-h" -o "$1" == "--help" ]); then
  echo "build-image <profile> <reg username> <reg password> <root directory>"
  echo " profile: 대상서버 프로파일명:ex)dev,prod"
  echo " reg username: container image registry username "
  echo " reg password: container image registry password "
  echo " root directory: project의 최상위 디렉토리. '.'은 현재 디렉토리 의미함. "
  echo " ex) ./build-image prod user1 password1 ~/work"
  echo " ex) ./build-image prod user1 password1 ."
  exit 2
fi

profile=$1
username=$2
password=$3
basedir=$4

# set variables from config.properties: converted from '.' to '_'
eval $(${basedir}/cicd/setenv ${basedir}/src/main/resources/config/application-common.properties)
eval $(${basedir}/cicd/setenv ${basedir}/src/main/resources/config/application-${profile}.properties)

# build image
echo "image: ${image_registry}/${image_project}/${image_repository}:${image_tag}"
docker build -f ${basedir}/cicd/Dockerfile -t ${image_registry}/${image_project}/${image_repository}:${image_tag} ${basedir}

# login image registry to push image: parameters are provided from bamboo pipeline.
docker login ${image_registry} -u  ${username} -p ${password}
if [ $? == 1 ]; then
  echo "****** FAIL to login image registry: username is $1"
  exit 2
fi

# clone image as 'latest'
docker tag ${image_registry}/${image_project}/${image_repository}:${image_tag} ${image_registry}/${image_project}/${image_repository}:latest

# push them
docker push ${image_registry}/${image_project}/${image_repository}:${image_tag}
docker push ${image_registry}/${image_project}/${image_repository}:latest